<?php 
    $page -> setTitle('Запрашиваемая страница не найдена!'); 
	$page -> addScript("js/index.js");
?>
	<div class='margin_0_auto width4size'>
	  <div class='err_width_center margin_0_auto'>
	  	       <div class='clear'></div>
			  <div class='after_err_height'></div>
			   <div class='clear'></div>
			  <div class='err_text'>Ошибка 404<div class='underfined'>Запрашиваемая cтраница <p>не найдена</p></div></div>
			  <div class='chair_error'></div>
			  <div class='clear'></div>
			  <div class='after_err_height'></div>
	  </div>
</div>
	
	