<div class='clear footer'>
	<div class='footer_delim_line'></div>
	<div class='footer_delim_logo'></div>
		<div class='float_left footer_left'>
			<?php print ($controller -> view!='views/index.phtml') ? '<a href="http://www.abz.dn.ua"  target="_blank" title="Создано abz.dn.ua - создание программного обеспечения в сжатые сроки">'.date('Y').'&nbsp;&copy;&nbsp;ВТЦ&nbsp;Мебельград</a>' : date('Y').'&nbsp;&copy;&nbsp;ВТЦ&nbsp;Мебельград';?>
			<p>Мебельный&nbsp;торговый&nbsp;центр</p>
		</div>
		<div class='float_left footer_left fotter_left_margin_left'>
			Украина,&nbsp;г.&nbsp;Донецк,&nbsp;ул.&nbsp;Сигова&nbsp;1б
			<div <?php print ($controller -> view=='views/contactsIndex.phtml') ? 'class="footer_link_contact footer_link_contact_now" >Как&nbsp;проехать' : 'class="footer_link_contact"><a href="contacts" title="Карта проезда">Карта&nbsp;проезда</a>' ?> </div>
		</div>
	<div class='float_right footer_right' >
		arenda@mg.dn.ua
		<p>info@mg.dn.ua</p>
	</div>
	<div class='float_right footer_right fotter_right_margin_right'>
		(062)&nbsp;387-19-82
		<p>(050)&nbsp;692-94-09</p>
	</div>
	<div class='float_right footer_right fotter_right_margin_right text_align_right'>
		Пн-Сб&nbsp;с&nbsp;10:00&nbsp;до&nbsp;19:00
		<p>Вс&nbsp;с&nbsp;10:00&nbsp;до&nbsp;18:00</p>
	</div>

</div>
<!-- Google Code for &#1058;&#1077;&#1075; &#1088;&#1077;&#1084;&#1072;&#1088;&#1082;&#1077;&#1090;&#1080;&#1085;&#1075;&#1072; -->
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 985630949;
var google_conversion_label = "UuewCKPywAQQ5ZH-1QM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/985630949/?value=0&amp;label=UuewCKPywAQQ5ZH-1QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>