<?php
    $page->setTitle("Мебельград - Аренда торговых помещений под магазины в Донецке");
	$page->addScript("js/index.js",'js/main_floor_hover.js');
	$page->setKeywords("");
	$page->setDescription("Выставочно-торговый центр «МебельградЪ» является крупнейшим специализированным торговым центром Донецка по продаже мебели и сопутствующих товаров.");
?>

<div class='content'>
	<div class='width4size margin_0_auto'>
		<div class='content_top_text'>Выставочно-торговый центр «Мебельград» является крупнейшим специализированным торговым центром Донецка по продаже мебели и сопутствующих товаров</div>
	</div>
    <div class='building' id='building'></div>
    <div class='width4size margin_0_auto'>
    	<div class='position_absolute' id='floor_animate'>
	    		<div class='floor_vid_1'></div>
	    		<div class='floor_vid_2'></div>
	    		<div class='floor_vid_3'></div>
	    	</div>
    	<div class='float_right'>
	    	<ul class='link_floor'>
	    		<li><a id='linkonefloor' href='/visitors/page/floor/3#3' title='3 этаж'>3 этаж</a></li>
	    		<li><a id='linktwofloor' href='/visitors/page/floor/2#2' title='2 этаж'>2 этаж</a></li>
	    		<li><a id='linkthrfloor' href='/visitors/page/floor/1#1' title='1 этаж'>1 этаж</a></li>
	    	</ul>
    	</div>
    	<div class='float_left'>
    	<div class='middle_main_pict_left_text'>
    		Вся продукция ведущих <p>отечественных и зарубежных мебельных компаний</p><p>собрана в выставочно-торговом центре «Мебельград»</p>
    	</div>
		</div> 
    	<div class='float_right'>
	    	<div class='middle_main_pict_right_text'>
	    		ВТЦ «Мебельград» предлагает</p>торговые площади для арендаторов</p>
	    	</div>
	    	
    	</div>
    </div>	
</div>